version: "3.0"

services:
  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'drink'
      MYSQL_USER: 'deb'
      MYSQL_PASSWORD: 'devpswd'
      MYSQL_ROOT_PASSWORD: 'devpswd'
    ports:
      - "3306:3306"
    volumes:
      - my-db:/var/lib/mysql

  spring:
    image: registry.nussi.net/drink-manager:1.0
    ports:
      - "80:8080"
    links:
      - db:database
    depends_on:
      - db

# Names our volume
volumes:
  my-db: